name: 06-1. Self-Hosted Linux Hello - Never run on public repo

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'What is your name?'
        required: true
        default: 'World'
        
jobs:
  say_hello: 
    # This will not work on a public repo unless allowed
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Say hello from self-hosted runner
        run: |
          echo "Hello ${{ github.event.inputs.name }}, from self-hosted runner!"
